### ISSUE TITLE
entityId  Client error: (404) Not Found

### ISSUE THREAD

**Issue by smjacques** [DDorch/Rthingsboard#6]
I'm facing the same issue Request failed with status Client error: (404) Not Found with my server, using the Rthingsboard 0.2.4.

The tb_api is running ok, but at keys = tb_api$getKeys(entityId = entityId).

Always get 404. I set both entity and dashboard as public, also tested another servers, but still seeing this issue.

Is there some solution to this?

**Comment by DDorch** [comment]
Hi @smjacques, 

Did you properly use the "Copy device Id" button and the "Copy customer ID" for getting these credentials?

The first is obtained from the "Devices" section:

![image](https://user-images.githubusercontent.com/14124454/121184884-cfe3d880-c865-11eb-9f0d-eb50b2174aae.png)

And the second from the "Customers" section:

![image](https://user-images.githubusercontent.com/14124454/121185207-1d604580-c866-11eb-9736-e5fbc1735a5a.png)

**Comment by DDorch** [comment]
If I try `keys = tb_api$getKeys(entityId = entityId)` with a wrong entity ID, I get an error 404. It could be your case also...

```r
library(Rthingsboard)
url = "http://scada.g-eau.fr"
publicId = "299cedc0-f3e9-11e8-9dbf-cbc1e37c11e3"
entityId = "very_wrong_id"
logger::log_threshold(logger::DEBUG)
keys = tb_api$getKeys(entityId = entityId)
```
The answer is:

```
Error in tb_api$getKeys(entityId = entityId) : 
  Request failed with status Server error: (500) Internal Server Error
```

**Comment by smjacques** [comment]
Thank you so much @DDorch 
My mistake was to create an entity and then use its ID.
Actually, I didn't realize that publicId is referring to User, and the entityId is the device ID.

Now it is running like a charm!
